//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback registerOperationCompleted;
    
    private System.Threading.SendOrPostCallback loginOperationCompleted;
    
    private System.Threading.SendOrPostCallback getPlayerOperationCompleted;
    
    private System.Threading.SendOrPostCallback createPlayerOperationCompleted;
    
    private System.Threading.SendOrPostCallback getHeroListOperationCompleted;
    
    private System.Threading.SendOrPostCallback getClothListOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddClothOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteClothOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddCardOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDeploymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveDeploymentOperationCompleted;
    


    
    /// <remarks/>
    public WebService1() {
        this.Url = "http://localhost:5731/WebService1.asmx";
    }
    
    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// <remarks/>
    public event registerCompletedEventHandler registerCompleted;
    
    /// <remarks/>
    public event loginCompletedEventHandler loginCompleted;
    
    /// <remarks/>
    public event getPlayerCompletedEventHandler getPlayerCompleted;
    
    /// <remarks/>
    public event createPlayerCompletedEventHandler createPlayerCompleted;
    
    /// <remarks/>
    public event getHeroListCompletedEventHandler getHeroListCompleted;
    
    /// <remarks/>
    public event getClothListCompletedEventHandler getClothListCompleted;
    
    /// <remarks/>
    public event AddClothCompletedEventHandler AddClothCompleted;
    
    /// <remarks/>
    public event DeleteClothCompletedEventHandler DeleteClothCompleted;
    
    /// <remarks/>
    public event AddCardCompletedEventHandler AddCardCompleted;
    
    /// <remarks/>
    public event GetDeploymentCompletedEventHandler GetDeploymentCompleted;
    
    /// <remarks/>
    public event SaveDeploymentCompletedEventHandler SaveDeploymentCompleted;
    
   public static WebService1 service;
    public static WebService1 Instance
    {
        get
        {
            if (service == null)
            {
                service = new WebService1();
            }
            return service;
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld() {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndHelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloWorldAsync() {
        this.HelloWorldAsync(null);
    }
    
    /// <remarks/>
    public void HelloWorldAsync(object userState) {
        if ((this.HelloWorldOperationCompleted == null)) {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg) {
        if ((this.HelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/register", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool register(string account, string password) {
        object[] results = this.Invoke("register", new object[] {
                    account,
                    password});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginregister(string account, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("register", new object[] {
                    account,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool Endregister(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void registerAsync(string account, string password) {
        this.registerAsync(account, password, null);
    }
    
    /// <remarks/>
    public void registerAsync(string account, string password, object userState) {
        if ((this.registerOperationCompleted == null)) {
            this.registerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterOperationCompleted);
        }
        this.InvokeAsync("register", new object[] {
                    account,
                    password}, this.registerOperationCompleted, userState);
    }
    
    private void OnregisterOperationCompleted(object arg) {
        if ((this.registerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.registerCompleted(this, new registerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string login(string account, string password) {
        object[] results = this.Invoke("login", new object[] {
                    account,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginlogin(string account, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("login", new object[] {
                    account,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endlogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void loginAsync(string account, string password) {
        this.loginAsync(account, password, null);
    }
    
    /// <remarks/>
    public void loginAsync(string account, string password, object userState) {
        if ((this.loginOperationCompleted == null)) {
            this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
        }
        this.InvokeAsync("login", new object[] {
                    account,
                    password}, this.loginOperationCompleted, userState);
    }
    
    private void OnloginOperationCompleted(object arg) {
        if ((this.loginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPlayer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Player getPlayer(string key) {
        object[] results = this.Invoke("getPlayer", new object[] {
                    key});
        return ((Player)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetPlayer(string key, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getPlayer", new object[] {
                    key}, callback, asyncState);
    }
    
    /// <remarks/>
    public Player EndgetPlayer(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Player)(results[0]));
    }
    
    /// <remarks/>
    public void getPlayerAsync(string key) {
        this.getPlayerAsync(key, null);
    }
    
    /// <remarks/>
    public void getPlayerAsync(string key, object userState) {
        if ((this.getPlayerOperationCompleted == null)) {
            this.getPlayerOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPlayerOperationCompleted);
        }
        this.InvokeAsync("getPlayer", new object[] {
                    key}, this.getPlayerOperationCompleted, userState);
    }
    
    private void OngetPlayerOperationCompleted(object arg) {
        if ((this.getPlayerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getPlayerCompleted(this, new getPlayerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createPlayer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Player createPlayer(string key, string name, int initCard) {
        object[] results = this.Invoke("createPlayer", new object[] {
                    key,
                    name,
                    initCard});
        return ((Player)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreatePlayer(string key, string name, int initCard, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createPlayer", new object[] {
                    key,
                    name,
                    initCard}, callback, asyncState);
    }
    
    /// <remarks/>
    public Player EndcreatePlayer(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Player)(results[0]));
    }
    
    /// <remarks/>
    public void createPlayerAsync(string key, string name, int initCard) {
        this.createPlayerAsync(key, name, initCard, null);
    }
    
    /// <remarks/>
    public void createPlayerAsync(string key, string name, int initCard, object userState) {
        if ((this.createPlayerOperationCompleted == null)) {
            this.createPlayerOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreatePlayerOperationCompleted);
        }
        this.InvokeAsync("createPlayer", new object[] {
                    key,
                    name,
                    initCard}, this.createPlayerOperationCompleted, userState);
    }
    
    private void OncreatePlayerOperationCompleted(object arg) {
        if ((this.createPlayerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createPlayerCompleted(this, new createPlayerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getHeroList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Card[] getHeroList(int userId, string key) {
        object[] results = this.Invoke("getHeroList", new object[] {
                    userId,
                    key});
        return ((Card[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetHeroList(int userId, string key, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getHeroList", new object[] {
                    userId,
                    key}, callback, asyncState);
    }
    
    /// <remarks/>
    public Card[] EndgetHeroList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Card[])(results[0]));
    }
    
    /// <remarks/>
    public void getHeroListAsync(int userId, string key) {
        this.getHeroListAsync(userId, key, null);
    }
    
    /// <remarks/>
    public void getHeroListAsync(int userId, string key, object userState) {
        if ((this.getHeroListOperationCompleted == null)) {
            this.getHeroListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHeroListOperationCompleted);
        }
        this.InvokeAsync("getHeroList", new object[] {
                    userId,
                    key}, this.getHeroListOperationCompleted, userState);
    }
    
    private void OngetHeroListOperationCompleted(object arg) {
        if ((this.getHeroListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getHeroListCompleted(this, new getHeroListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getClothList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Cloth[] getClothList(int userId, string key) {
        object[] results = this.Invoke("getClothList", new object[] {
                    userId,
                    key});
        return ((Cloth[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetClothList(int userId, string key, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getClothList", new object[] {
                    userId,
                    key}, callback, asyncState);
    }
    
    /// <remarks/>
    public Cloth[] EndgetClothList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Cloth[])(results[0]));
    }
    
    /// <remarks/>
    public void getClothListAsync(int userId, string key) {
        this.getClothListAsync(userId, key, null);
    }
    
    /// <remarks/>
    public void getClothListAsync(int userId, string key, object userState) {
        if ((this.getClothListOperationCompleted == null)) {
            this.getClothListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetClothListOperationCompleted);
        }
        this.InvokeAsync("getClothList", new object[] {
                    userId,
                    key}, this.getClothListOperationCompleted, userState);
    }
    
    private void OngetClothListOperationCompleted(object arg) {
        if ((this.getClothListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getClothListCompleted(this, new getClothListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddCloth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Cloth AddCloth(int userId, string key, int typeCode, int gridCode) {
        object[] results = this.Invoke("AddCloth", new object[] {
                    userId,
                    key,
                    typeCode,
                    gridCode});
        return ((Cloth)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddCloth(int userId, string key, int typeCode, int gridCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddCloth", new object[] {
                    userId,
                    key,
                    typeCode,
                    gridCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public Cloth EndAddCloth(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Cloth)(results[0]));
    }
    
    /// <remarks/>
    public void AddClothAsync(int userId, string key, int typeCode, int gridCode) {
        this.AddClothAsync(userId, key, typeCode, gridCode, null);
    }
    
    /// <remarks/>
    public void AddClothAsync(int userId, string key, int typeCode, int gridCode, object userState) {
        if ((this.AddClothOperationCompleted == null)) {
            this.AddClothOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddClothOperationCompleted);
        }
        this.InvokeAsync("AddCloth", new object[] {
                    userId,
                    key,
                    typeCode,
                    gridCode}, this.AddClothOperationCompleted, userState);
    }
    
    private void OnAddClothOperationCompleted(object arg) {
        if ((this.AddClothCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddClothCompleted(this, new AddClothCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteCloth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int DeleteCloth(int userId, string key, int clothId) {
        object[] results = this.Invoke("DeleteCloth", new object[] {
                    userId,
                    key,
                    clothId});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteCloth(int userId, string key, int clothId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteCloth", new object[] {
                    userId,
                    key,
                    clothId}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndDeleteCloth(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteClothAsync(int userId, string key, int clothId) {
        this.DeleteClothAsync(userId, key, clothId, null);
    }
    
    /// <remarks/>
    public void DeleteClothAsync(int userId, string key, int clothId, object userState) {
        if ((this.DeleteClothOperationCompleted == null)) {
            this.DeleteClothOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteClothOperationCompleted);
        }
        this.InvokeAsync("DeleteCloth", new object[] {
                    userId,
                    key,
                    clothId}, this.DeleteClothOperationCompleted, userState);
    }
    
    private void OnDeleteClothOperationCompleted(object arg) {
        if ((this.DeleteClothCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteClothCompleted(this, new DeleteClothCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Card AddCard(int userId, string key, int cardCode) {
        object[] results = this.Invoke("AddCard", new object[] {
                    userId,
                    key,
                    cardCode});
        return ((Card)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddCard(int userId, string key, int cardCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddCard", new object[] {
                    userId,
                    key,
                    cardCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public Card EndAddCard(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Card)(results[0]));
    }
    
    /// <remarks/>
    public void AddCardAsync(int userId, string key, int cardCode) {
        this.AddCardAsync(userId, key, cardCode, null);
    }
    
    /// <remarks/>
    public void AddCardAsync(int userId, string key, int cardCode, object userState) {
        if ((this.AddCardOperationCompleted == null)) {
            this.AddCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCardOperationCompleted);
        }
        this.InvokeAsync("AddCard", new object[] {
                    userId,
                    key,
                    cardCode}, this.AddCardOperationCompleted, userState);
    }
    
    private void OnAddCardOperationCompleted(object arg) {
        if ((this.AddCardCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddCardCompleted(this, new AddCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeployment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Deployment GetDeployment(int userId, string key) {
        object[] results = this.Invoke("GetDeployment", new object[] {
                    userId,
                    key});
        return ((Deployment)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDeployment(int userId, string key, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDeployment", new object[] {
                    userId,
                    key}, callback, asyncState);
    }
    
    /// <remarks/>
    public Deployment EndGetDeployment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Deployment)(results[0]));
    }
    
    /// <remarks/>
    public void GetDeploymentAsync(int userId, string key) {
        this.GetDeploymentAsync(userId, key, null);
    }
    
    /// <remarks/>
    public void GetDeploymentAsync(int userId, string key, object userState) {
        if ((this.GetDeploymentOperationCompleted == null)) {
            this.GetDeploymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeploymentOperationCompleted);
        }
        this.InvokeAsync("GetDeployment", new object[] {
                    userId,
                    key}, this.GetDeploymentOperationCompleted, userState);
    }
    
    private void OnGetDeploymentOperationCompleted(object arg) {
        if ((this.GetDeploymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDeploymentCompleted(this, new GetDeploymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveDeployment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool SaveDeployment(int userId, string key, int grid, int id, int type) {
        object[] results = this.Invoke("SaveDeployment", new object[] {
                    userId,
                    key,
                    grid,
                    id,
                    type});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveDeployment(int userId, string key, int grid, int id, int type, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveDeployment", new object[] {
                    userId,
                    key,
                    grid,
                    id,
                    type}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndSaveDeployment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void SaveDeploymentAsync(int userId, string key, int grid, int id, int type) {
        this.SaveDeploymentAsync(userId, key, grid, id, type, null);
    }
    
    /// <remarks/>
    public void SaveDeploymentAsync(int userId, string key, int grid, int id, int type, object userState) {
        if ((this.SaveDeploymentOperationCompleted == null)) {
            this.SaveDeploymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDeploymentOperationCompleted);
        }
        this.InvokeAsync("SaveDeployment", new object[] {
                    userId,
                    key,
                    grid,
                    id,
                    type}, this.SaveDeploymentOperationCompleted, userState);
    }
    
    private void OnSaveDeploymentOperationCompleted(object arg) {
        if ((this.SaveDeploymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveDeploymentCompleted(this, new SaveDeploymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Player {
    
    private int idField;
    
    private int account_idField;
    
    private string nameField;
    
    private int levelField;
    
    private int expField;
    
    private int moneyField;
    
    private int goldField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int account_id {
        get {
            return this.account_idField;
        }
        set {
            this.account_idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public int level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    public int exp {
        get {
            return this.expField;
        }
        set {
            this.expField = value;
        }
    }
    
    /// <remarks/>
    public int money {
        get {
            return this.moneyField;
        }
        set {
            this.moneyField = value;
        }
    }
    
    /// <remarks/>
    public int gold {
        get {
            return this.goldField;
        }
        set {
            this.goldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class DeploymentGridModel {
    
    private int cardIdField;
    
    private int swordIdField;
    
    private int hatIdField;
    
    private int clothIdField;
    
    private int bookIdField;
    
    private int shooeIdField;
    
    private int horseIdField;
    
    /// <remarks/>
    public int cardId {
        get {
            return this.cardIdField;
        }
        set {
            this.cardIdField = value;
        }
    }
    
    /// <remarks/>
    public int swordId {
        get {
            return this.swordIdField;
        }
        set {
            this.swordIdField = value;
        }
    }
    
    /// <remarks/>
    public int hatId {
        get {
            return this.hatIdField;
        }
        set {
            this.hatIdField = value;
        }
    }
    
    /// <remarks/>
    public int clothId {
        get {
            return this.clothIdField;
        }
        set {
            this.clothIdField = value;
        }
    }
    
    /// <remarks/>
    public int bookId {
        get {
            return this.bookIdField;
        }
        set {
            this.bookIdField = value;
        }
    }
    
    /// <remarks/>
    public int shooeId {
        get {
            return this.shooeIdField;
        }
        set {
            this.shooeIdField = value;
        }
    }
    
    /// <remarks/>
    public int horseId {
        get {
            return this.horseIdField;
        }
        set {
            this.horseIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Deployment {
    
    private int idField;
    
    private int user_idField;
    
    private DeploymentGridModel grid1Field;
    
    private DeploymentGridModel grid2Field;
    
    private DeploymentGridModel grid3Field;
    
    private DeploymentGridModel grid4Field;
    
    private DeploymentGridModel grid5Field;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int user_id {
        get {
            return this.user_idField;
        }
        set {
            this.user_idField = value;
        }
    }
    
    /// <remarks/>
    public DeploymentGridModel grid1 {
        get {
            return this.grid1Field;
        }
        set {
            this.grid1Field = value;
        }
    }
    
    /// <remarks/>
    public DeploymentGridModel grid2 {
        get {
            return this.grid2Field;
        }
        set {
            this.grid2Field = value;
        }
    }
    
    /// <remarks/>
    public DeploymentGridModel grid3 {
        get {
            return this.grid3Field;
        }
        set {
            this.grid3Field = value;
        }
    }
    
    /// <remarks/>
    public DeploymentGridModel grid4 {
        get {
            return this.grid4Field;
        }
        set {
            this.grid4Field = value;
        }
    }
    
    /// <remarks/>
    public DeploymentGridModel grid5 {
        get {
            return this.grid5Field;
        }
        set {
            this.grid5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Cloth {
    
    private int idField;
    
    private int user_idField;
    
    private int typeField;
    
    private int grid_idField;
    
    private int levelField;
    
    private int defendField;
    
    private int magicField;
    
    private int apField;
    
    private int hpField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int user_id {
        get {
            return this.user_idField;
        }
        set {
            this.user_idField = value;
        }
    }
    
    /// <remarks/>
    public int type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public int grid_id {
        get {
            return this.grid_idField;
        }
        set {
            this.grid_idField = value;
        }
    }
    
    /// <remarks/>
    public int level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    public int defend {
        get {
            return this.defendField;
        }
        set {
            this.defendField = value;
        }
    }
    
    /// <remarks/>
    public int magic {
        get {
            return this.magicField;
        }
        set {
            this.magicField = value;
        }
    }
    
    /// <remarks/>
    public int ap {
        get {
            return this.apField;
        }
        set {
            this.apField = value;
        }
    }
    
    /// <remarks/>
    public int hp {
        get {
            return this.hpField;
        }
        set {
            this.hpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Card {
    
    private int idField;
    
    private int user_idField;
    
    private int gd_codeField;
    
    private int levelField;
    
    private int expField;
    
    private int additionalField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int user_id {
        get {
            return this.user_idField;
        }
        set {
            this.user_idField = value;
        }
    }
    
    /// <remarks/>
    public int gd_code {
        get {
            return this.gd_codeField;
        }
        set {
            this.gd_codeField = value;
        }
    }
    
    /// <remarks/>
    public int level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    public int exp {
        get {
            return this.expField;
        }
        set {
            this.expField = value;
        }
    }
    
    /// <remarks/>
    public int additional {
        get {
            return this.additionalField;
        }
        set {
            this.additionalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void registerCompletedEventHandler(object sender, registerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class registerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal registerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void getPlayerCompletedEventHandler(object sender, getPlayerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getPlayerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getPlayerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Player Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Player)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void createPlayerCompletedEventHandler(object sender, createPlayerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createPlayerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createPlayerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Player Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Player)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void getHeroListCompletedEventHandler(object sender, getHeroListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getHeroListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getHeroListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Card[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Card[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void getClothListCompletedEventHandler(object sender, getClothListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getClothListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getClothListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Cloth[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Cloth[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void AddClothCompletedEventHandler(object sender, AddClothCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddClothCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AddClothCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Cloth Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Cloth)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void DeleteClothCompletedEventHandler(object sender, DeleteClothCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteClothCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteClothCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void AddCardCompletedEventHandler(object sender, AddCardCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AddCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Card Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Card)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetDeploymentCompletedEventHandler(object sender, GetDeploymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDeploymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDeploymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Deployment Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Deployment)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void SaveDeploymentCompletedEventHandler(object sender, SaveDeploymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SaveDeploymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SaveDeploymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}
